title: Guaraná
description: Documentação do projeto Guaraná
theme: just-the-docs

url: https://github.com/GPMM/Guarana2

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
